### ISSUE TITLE
Rename MockFirebase to MockFirestore

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#30]
Maybe you could Rename `MockFirebase` to `MockFirestore` for better accuracy. But it's just an idea. Feel free to close.

**Comment by rmmmp** [comment]
`MockFirebase` actually represents `firebase` itself.

e.g.

```javascript
const firebase = new MockFirebase(fixtureData);
const db = firebase.firestore();

db.collection('users').add({ ... });
```
