### ISSUE TITLE
Show how to test an insert / patch / batch

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#31]
Currently the Readme only shows how to create a new MockFirebase with 
`new MockFirebase(fixtureData);`

However, there are no sample of how to test a firestore insert, patch or firestore.batch()!

I'd love to see how to do that! Best regards.

**Comment by rmmmp** [comment]
Nothing should change within your business logic. Firestore inserts, patch, batch, etc. should still be the same. You just have to replace the Firebase instance you're using with `MockFirebase`. That depends on how you consume Firebase.

e.g.

If you're using `firebase` as-is like a global variable you could do:

```javascript
window.firebase = new MockFirebase(fixtureData);

const db = firebase.firestore();

db.collection('users').add({ ... });
```

If you're passing `firebase` as a param in a function you could do:

```javascript
function foo(firebase) {
  const db = firebase.firestore();

  db.collection('users').add({ ... });
}

foo(new MockFirebase(fixtureData));
```

**Comment by mesqueeb** [comment]
#32
