### ISSUE TITLE
`doc.data()` is not working

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#33]
1. I try to await a `docref.get()`
2. I try to console.log the `doc.data()` →　but it won't work?

See screenshot below:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/3253920/46711991-d28f6980-cc89-11e8-9cf2-ad88c7f68326.png">

**Comment by rmmmp** [comment]
What does your fixture data look like? I don't think the document exists that's why it's returning undefined.

**Comment by mesqueeb** [comment]
@rmmmp You are right, based on how my async actions are set up, I had to wait for a second before checking.

The weird thing is, now it works in wallaby (instant test feedback) but not in ava console. XD

Works in wallaby:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3253920/46713311-d1156f80-cc90-11e8-95ae-0d4f45219e9e.png">

But not in Ava:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/3253920/46713321-e8545d00-cc90-11e8-8b69-1e8d0df7c7fd.png">

But I guess this is not a problem with your mock.

**Comment by mesqueeb** [comment]
@rmmmp I'm not sure... all errors point towards your package so I'm kinda thinking it might have something to do with your package...?

**Comment by mesqueeb** [comment]
@rmmmp I should open a new issue, since this is unrelated to the original post.
