### ISSUE TITLE
Error: Invalid document reference. Document references must have an even number of segments, but  has 1.

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#34]
For me, at one part it works in `Wallaby` (instant test feedback) but not in `ava`. See the console.logs:

Works in wallaby:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3253920/46713311-d1156f80-cc90-11e8-95ae-0d4f45219e9e.png">

But not in Ava:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/3253920/46713321-e8545d00-cc90-11e8-8b69-1e8d0df7c7fd.png">

**Comment by rmmmp** [comment]
Sorry. I dunno what Wallaby or Ava is. If it's working for one, maybe there's a specific issue in your code on the other environment.

**Comment by mesqueeb** [comment]
@rmmmp what's your recommended testing library for this mock? Jest?

**Comment by rmmmp** [comment]
It should work with any. Can you post a snippet on what code doesn't work? Also have you tried it in Firestore itself.

What the issue is saying is that you're trying to point to a document but in fact, you're pointing to a collection.

**Comment by mesqueeb** [comment]
Does the document need to be registered on beforehand in the fixtureData? Because i'm trying to add the doc first to the mock  and then retrieving the doc from the mock. This all happens inside the test so I didn't put it in the fixtureData. 

I'm especially confused about the "path" that your error should log, which is apparently an empty string in my case. 

> even number of segments but  has 1.

You see the double space?

**Comment by rmmmp** [comment]
Please post code snippet so I can investigate

**Comment by mesqueeb** [comment]
Closing for now. It was probably an ava config issue.
