### ISSUE TITLE
Error: firestore.FieldValue.delete is not a function

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#37]
Could it be that this is not implemented?
> Firebase$$1.firestore.FieldValue.delete is not a function

**Comment by rmmmp** [comment]
Yes it isn't implemented right now. I'll try to find some time to do it.

**Comment by rmmmp** [comment]
Please try out #38 and see if that works for you. I'll merge it once it is.

**Comment by mesqueeb** [comment]
@rmmmp Works like a charm. (though not on nested-props) Please merge! ♡
