### ISSUE TITLE
[Request] support "Update fields in nested objects"

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#39]
I use a lot of this in my apps.
Please see documentation [here](https://firebase.google.com/docs/firestore/manage-data/add-data): chapter called **"Update fields in nested objects"**.

I use things like:
```js
docRef
.set({   // or   .update({
    "favorites.color": "Red"
    // or
    "favorites.animal": Firebase.firestore.FieldValue.delete()
})
```

**Comment by rmmmp** [comment]
Right. I'll look into implementing this. Note that the nested objects only work for `update()`. The `'favorites.color'` will literally be saved as that key when using it in `set()`.

**Comment by rmmmp** [comment]
#43 supports this feature.

Travis builds are still paused right now due to the GitHub issue. Once I see all green, I'll merge the PR. In the meantime, you can test that branch and see if it works for your use-cases.

**Comment by mesqueeb** [comment]
@rmmmp cool i'll try it out! Thanks So much!! 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kimroen** [comment]
> Note that the nested objects only work for `update()`. The `'favorites.color'` will literally be saved as that key when using it in `set()`.

@mikkopaderes Do you mind expanding on why this is? I'm not sure I understand.

**Comment by mikkopaderes** [comment]
@kimroen that's how it works with Cloud Firestore. This question is really for the Firebase team not me 👅
