### ISSUE TITLE
`offset` method missing

### ISSUE THREAD

**Issue by Dabolus** [rmmmp/mock-cloud-firestore#45]
First of all, thanks for the awesome work, it is really useful!

While writing some tests using your mock Firestore i noticed that the `offset` method is missing, e.g. trying to execute something like this:
```javascript
db
  .collection('documents')
  .limit(50)
  .offset(10)
  .get();
```
Works using the real Firestore library, while using your mock Firestore I get:
`[TypeError: this.db.collection(...).limit(...).offset is not a function]`

Is there any chance to have it implemented?

**Comment by rmmmp** [comment]
I'll have to see first since offset is not available in client sdks. It's also not a popular feature due to pricing issue. See https://github.com/firebase/firebase-js-sdk/issues/479

**Comment by Dabolus** [comment]
Oh, didn't know it, thanks for pointing this out! Closing since I migrated away from the `offset` method and so I don't need it anymore.
