### ISSUE TITLE
Cannot find module './_export'

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#51]
I have this with 0.8.0 and not with 0.7.0.
```
  /.../node_modules/mock-cloud-firestore/lib/mock-cloud-firestore.js:67

  Error: Cannot find module './_export'
```
I'm not sure if this is a problem on my end?

**Comment by rmmmp** [comment]
Hmm. Must be related to me using rollup. What env are you developing on? Nodejs or a browser?

**Comment by rmmmp** [comment]
Yeah this seems to be a misconfiguration in Rollup. I should've also tested the build for node.js not just for the browser. Sorry about that.

I'll publish a quick fix when I get to my laptop.

**Comment by mesqueeb** [comment]
Thanks. I develop with nodejs and use rollup to prepare my test files. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
