### ISSUE TITLE
Initializing an empty store requires empty object

### ISSUE THREAD

**Issue by kimroen** [rmmmp/mock-cloud-firestore#52]
Hi! This is certainly debatable, so please consider this more of a suggestion rather than a bug report.

I am aware that you can create a mock firestore with some fixture data by passing in an object to the initializer:

```js
const fixtureData = {
  __collection__: {
    users: {
      __doc__: {
        user_a: {
          age: 15,
          username: 'user_a'
        },
        user_b: {
          age: 20,
          username: 'user_b'
        }
      }
    }
  }
}
const db = new MockFirebase(fixtureData).firestore();

// Do stuff with the database
```

I prefer using the Firestore API to add my test data though, so I'd do it like this:

```js
const db = new MockFirebase().firestore();

await db.collection('users').add({ age: 15, username: 'user_a' });
await db.collection('users').add({ age: 20, username: 'user_b' });

// Do stuff with the database
```

This doesn't work, because you need to pass in the fixture data to the `MockFirebase` initializer. So instead, I need to write this:

```diff
-const db = new MockFirebase().firestore();
+const db = new MockFirebase({}).firestore();
```

This isn't the worst thing in the world, but because the initializer doesn't complain about the lack of provided arguments, updated data is simply ignored, which leads to a lot of confusing test failures.

To avoid this and to make the library feel nicer in use, I suggest we make the initializer assign the internal data to an empty object if nothing was provided, so the above works.

**Comment by rmmmp** [comment]
Great idea. Will do this. Thanks.
