### ISSUE TITLE
[Bug] Cannot use 'prop.with.multiple.dots.in.name'

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#55]
So after another two days of trying to get all my tests to work properly, finding some of my own bugs, and studying your library a bit more. I found a new bug with 0.8.

Currently updating props like so: `'prop.name': 'new value'` works perfect, also with deleting.

However, if there is a prop non-existent → a doc doesn't have the property `prop` and also no property called `prop.name`, it will give an error.

This means that currently updating like so `docRef.update({'prop.name': 'new value'})` only works if there already is a property like so `prop: {name: 'already here'}` on the doc.

**Comment by rmmmp** [comment]
What's the error message?

**Comment by mesqueeb** [comment]
It can't find 'name' on 'prop'

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Hold on i'm back in the office in two hours i'll try replicating it is a test inside your library then. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rmmmp** [comment]
Hmm. That's weird. I have a test case for updating a unexisting nested prop and it passes. I guess I'll wait for your replication then. Thanks.

**Comment by mesqueeb** [comment]
@rmmmp I think you only tested with props with just 1 dot.
This test fails and has that error I said:

```js
  QUnit.test('should update props with .', async (assert) => {
      // Arrange
      const db = mockFirebase.firestore();
      const batch = db.batch();
      const ref1 = db.collection('users').doc();
      batch.set(ref1, { username: 'new_user' });
      // Act
      await batch.commit();
      // Assert
      const snapshot1 = await ref1.get();
      assert.deepEqual(snapshot1.data(), { username: 'new_user' });
      // Act 2
      const batch2 = db.batch();
      batch2.update(ref1, { 'a.prop.with.dots': true });
      await batch2.commit();
      // Assert 2
      const snapshot2 = await ref1.get();
      assert.deepEqual(snapshot2.data(), { username: 'new_user', 'a.prop.with.dots': true });
    });
```

If you can fix this I don't think I will have any more bugs for you. : D

**Comment by rmmmp** [comment]
@mesqueeb no worries. Thanks for being patient with investigating these bugs.

I've pushed a quick fix in the master branch. You can use that temporarily until I release a new version later within the day.

**Comment by mesqueeb** [comment]
@rmmmp I just looked at your tests, but I'm a bit confused.
In my thought the to-be-expected pattern is:
```js
// original object
{existing: {deep: {prop: 1}}}
// update like so:
docRef.update({'existing.deep.prop': 2, 'new.deep.prop': true})
// should result in firestore saving this data:
{existing: {deep: {prop: 2}}, 'new.deep.prop': true}
```
This above is the to-be-expected-pattern right?

This wasn't immediately clear from your tests, but maybe it's just me. : D

If you could give me your thoughts, that'd be great!

**Comment by rmmmp** [comment]
The `new.deep.prop` would nest it in objects when you use `update()`. If you use `set()` however, it wouldn't. You can try it in Firestore itself to see it for yourself.

**Comment by mesqueeb** [comment]
Oh I never knew this!! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rmmmp** [comment]
And just to add one more, the same holds true even if you use `merge: true` in your `set()`

**Comment by mesqueeb** [comment]
Thanks for everything! Let me know when you update on npm. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@rmmmp Don't forget to `npm publish`! : D

**Comment by rmmmp** [comment]
Done
