### ISSUE TITLE
firestore.collection should allow for slashes in the collectionPath

### ISSUE THREAD

**Issue by richzaleski** [rmmmp/mock-cloud-firestore#8]
Currently with the example data provided you only return a collection when the id is passed as "users".
It will not return a collection for "/users".

https://cloud.google.com/nodejs/docs/reference/firestore/0.13.x/Firestore#collection

**Comment by rmmmp** [comment]
Yup the library works like that. Is it not for you or maybe the README is confusing?

**Comment by richzaleski** [comment]
I like the library but it should work according to the api specifications.

**Comment by rmmmp** [comment]
Interesting. I didn't know you can use slashes to refer to a collection. I'll try to find some time to work on this. Thanks!
